export const FLIGHTS_LOAD_START = 'FLIGHTS_LOAD_START';
export const FLIGHTS_LOAD_SUCCESS = 'FLIGHTS_LOAD_SUCCESS';
export const FLIGHTS_LOAD_FAIL = 'FLIGHTS_LOAD_FAIL';
export const SELECTED_CARRIER_CHANGE = 'SELECTED_CARRIER_CHANGE';
